import os

Import('env')

if env['AllDlls'] or ( 'DiseaseDll' in env and env[ 'DiseaseDll' ] !="" ):
    print("ERROR: component tests only supported in monolithic")
else:
    print( env["Disease"] )

    testsSrcFiles = [
        "AdherentDrugTest.cpp",
        "AssortivityTest.cpp",
        "BaseEventReportTest.cpp",
        "BehaviorPfaTest.cpp",
        "CampaignEventByYearTest.cpp",
        "CommunityHealthWorkerEventCoordinatorTest.cpp",
        "componentTests.cpp",
        "ConcurrencyParametersTest.cpp",
        "ConfigureTest.cpp",
        "DelayedInterventionTest.cpp",
        "FileSystemTest.cpp",
        "FlowControllerImplTest.cpp",
        "GenomeMarkersTest.cpp",
        "HIVARTStagingByCD4DiagnosticTest.cpp",
        "HIVARTStagingCD4AgnosticDiagnosticTest.cpp",
        "HIVDrawBloodTest.cpp",
        "HIVSimpleDiagnosticTest.cpp",
        "IncidenceEventCoordinatorTest.cpp",
        "InterventionForCurrentPartnersTest.cpp",
        "InterpolatedValueMapTest.cpp",
        "JsonObjectDemogTest.cpp",
        "LarvalHabitatMultiplierTest.cpp",
        "LoadBalanceSchemeTest.cpp",
        "MalariaDrugTypeParametersTest.cpp",
        "MathFunctionsTest.cpp",
        "MigrateIndividualsTest.cpp",
        "MigrationTest.cpp",
        "NChooserEventCoordinatorTest.cpp",
        "NodeDemographicsTest.cpp",
        "NodePropertiesTest.cpp",
        "PairFormationParametersImplTest.cpp",
        "PairFormationStatsImplTest.cpp",
        "PrngTest.cpp",
        "ProgramOptionsTest.cpp",
        "PropertiesTest.cpp",
        "RandomNumberGeneratorFactoryTest.cpp",
        "RateTableImplTest.cpp",
        "RelationshipParametersTest.cpp",
        "ReportUtilitiesMalariaTest.cpp",
        "ReportUtilitiesTest.cpp",
        #"SerializationTest.cpp",
        "SerializationParametersTest.cpp",
        "SigmoidTest.cpp",
        "STIIsPostDebutTest.cpp",
        "TestChiSquare.cpp",
        "TransmissionGroupsTest.cpp",
        "WaningEffectComboTest.cpp",
        "WaningEffectMapTest.cpp",
        "FakeLogger.cpp"
    ]


    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # !!! These linker flags are here so that they are not included with the DLLs.  !!!
    # !!! These are only for the EXE.                                               !!!
    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    erad_env = env.Clone()
    erad_env.Append( EXTRACPPPATH=["#/UnitTest++/src"])
    erad_env.Append( LIBPATH=[ "$BUILD_DIR/UnitTest++" ] )
    erad_env.Append(LIBS=["unitTest"])

    if os.sys.platform == 'win32':
        erad_env.Append( LINKFLAGS=[ "/STACK:\"100000000,100000000\"" ] )
        erad_env.Append( LINKFLAGS=[ "/DELAYLOAD:python3.dll" ] )
        erad_env.Append( LIBS=["delayimp.lib"] )
        erad_env.Append(LIBPATH = ["$BUILD_DIR/Eradication"])
        erad_env.Append(LIBS=["/WHOLEARCHIVE:coreLib"])
    else:
        if env["Debug"]:
            erad_env.Append(LINKFLAGS=["-Wl,--whole-archive,build/x64/Debug/Eradication/libcoreLib.a,--no-whole-archive"])
        else:
            erad_env.Append(LINKFLAGS=["-Wl,--whole-archive,build/x64/Release/Eradication/libcoreLib.a,--no-whole-archive"])

    # Monolithic
    testsExe = erad_env.Program('componentTests', testsSrcFiles)
    erad_env.Depends(testsExe, erad_env.Alias("CoreLibAlias") )
    erad_env.Depends(testsExe, erad_env.Alias("UnitTestAlias") )
