[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "emod-generic"
dynamic = ["version"]
description = "PyPI distribution of EMOD-Generic files."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Kurt Frey", email="kurt.frey@gatesfoundation.org" },
]
keywords = ["modeling", "IDM"]
dependencies = [
]
license = "MIT"
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.optional-dependencies]
docs = [
    "mkdocs-material",
    "mkdocs-include-markdown-plugin",
    "mkdocstrings-python",
    "mkdocs-autoapi",
    "mkdocs-glightbox",
    "mkdocs-table-reader-plugin",
]
lint = [
]
test = [
    "pandas",
    "scipy",
    "matplotlib",
    "lz4",
    "python-snappy",
]

[project.urls]
Repository = "https://github.com/EMOD-Hub/EMOD-Generic"
Documentation = "https://emod.idmod.org/EMOD-Generic/"
Issues = "https://github.com/EMOD-Hub/EMOD-Generic/issues"

[tool.setuptools.package-data]
"*" = ["*.zip"]

[tool.setuptools.dynamic]
version = {file = ["src/version"]}
