[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "emod-generic"
dynamic = ["version"]
description = "PyPI distribution of EMOD-Generic files."
license = "MIT"
authors = [
    { name="Kurt Frey", email="kurt.frey@gatesfoundation.org" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.optional-dependencies]
docs = [
    "setuptools",
    "sphinxext.remoteliteralinclude",
    "sphinx",
    "sphinx-copybutton",
    "pydata-sphinx-theme",
    "plantweb",
    "sphinxcontrib-programoutput",
    "myst-parser",
    "pygithub"
]
tests = [
]

[project.urls]
Homepage = "https://www.idmod.org/tool/emod-generic/"
Documentation = "https://emod-hub.github.io/EMOD-Generic/"
Repository = "https://github.com/EMOD-Hub/EMOD-Generic"
Issues = "https://github.com/EMOD-Hub/EMOD-Generic/issues"

[tool.setuptools.package-data]
"*" = ["*.zip"]

[tool.setuptools.dynamic]
version = {file = ["src/version"]}
