name: Run scientific feature tests

on:
  # Allows manual run from the Actions tab
  workflow_dispatch:
    inputs:
      test_suite:
        required: true
        type: string
        default: 'generic_science'

jobs:
  build:
    name: Build and create artifacts
    uses: ./.github/workflows/reusable_build_archive.yml
    with:
      disease_type: 'All'
      science_test: '--TestSugar'
      dev_version: ''

  run-tests:
    name: Run scientific feature tests
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      path_exe: './build/x64/Release/Eradication'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download executable
        uses: actions/download-artifact@v7
        with:
          name: Eradication
          path: ${{ env.path_exe }}
      - name: Restore permissions
        run: |
          chmod +x ${{ env.path_exe }}/Eradication
      - name: Run tests
        uses: docker://ghcr.io/emod-hub/emod-ubuntu-runtime:latest
        with:
          args: "python3 ./Regression/regression_test.py ${{ inputs.test_suite }} --scons"
      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: Reports
          path: ./Regression/reports/
          retention-days: 7
