name: Run regression and component tests

on:
  # Allows manual run from the Actions tab
  workflow_dispatch:
    inputs:
      test_suite:
        required: true
        type: string
        default: 'generic'

jobs:
  build:
    name: Build and create artifacts
    uses: ./.github/workflows/build_archive.yml
    with:
      disease_type: 'All'
      science_test: ' '

  run-tests:
    name: Run regession and component tests
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      path_exe: './build/x64/Release/Eradication'
      path_comp_test: './build/x64/Release/componentTests'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download executable
        uses: actions/download-artifact@v7
        with:
          name: Eradication
          path: ${{ env.path_exe }}
      - name: Download component tests
        uses: actions/download-artifact@v7
        with:
          name: componentTests
          path: ${{ env.path_comp_test }}
      - name: Restore permissions
        run: |
          chmod +x ${{ env.path_exe }}/Eradication
          chmod +x ${{ env.path_comp_test }}/componentTests
      - name: Run tests
        uses: docker://docker-production.packages.idmod.org:443/idm/dtk-centos-buildenv:3.0
        with:
          args: "python3 regression_test.py ${{ inputs.test_suite }} --scons --component-tests --linux"
        working-directory: ./Regression
      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: Reports
          path: ./Regression/reports/
          retention-days: 7
